# Load packages
```{r, message=FALSE}
library(tidyverse)
library(hablar)
```

# Sample dict
```{r}
sample_dict <- c('ct15' = 'chimp',
                 'ct22' = 'chimp',
                 'ct28' = 'chimp',
                 'ct32' = 'chimp',
                 'gt21' = 'gorilla',
                 'gt22' = 'gorilla',
                 'gt43' = 'gorilla',
                 'hs25' = 'human',
                 'hs35' = 'human',
                 'hs50' = 'human',
                 'ht20' = 'human',
                 'ht45' = 'human',
                 'ht50' = 'human',
                 'ht55' = 'human',
                 'ht60' = 'human',
                 'ht65' = 'human')

```

# Functions
```{r}
#############################
# REF POSITIONS FOR CO EVENTS
#############################
ref_pos_co_events <- function(data, number_of_flanking_snps){
  before_vector <- c()
  after_vector <- c()
  for(i in seq(nrow(data))){
    jump_snp = data$jump_snp[i]
    snps = as.numeric(strsplit(data$snp_pos_in_read[i], ',')[[1]])
    jump_snp_index = which(jump_snp == snps)
    last_index = length(snps)
    second_flanking_before = snps[jump_snp_index - number_of_flanking_snps]
    second_flanking_after = snps[jump_snp_index + number_of_flanking_snps - 1]
    dist_to_flanking_before = jump_snp - second_flanking_before
    dist_to_flanking_after = second_flanking_after - jump_snp
    before_vector <- c(before_vector, dist_to_flanking_before)
    after_vector <- c(after_vector, dist_to_flanking_after)
}
return(list(before_vector, after_vector))
}
```
## First and last SNP
```{r}
first_last_snps <- function(data){
  first_snp_vector <- c()
  last_snp_vector <- c()
  for(i in seq(nrow(data))){
    jump_snp = data$jump_snp[i]
    snps = as.numeric(strsplit(data$snp_pos_in_read[i], ',')[[1]])
    jump_snp_index = which(jump_snp == snps)
    dist_to_first_snp <- snps[jump_snp_index] - snps[1]
    dist_to_last_snp <- snps[length(snps)] - snps[jump_snp_index]
    first_snp_vector <- c(first_snp_vector, dist_to_first_snp)
    last_snp_vector <- c(last_snp_vector, dist_to_last_snp)
  }
  return(list(first_snp_vector, last_snp_vector))
}
```

# Reference genomes
```{r}
# Human
chromosome_levels <- c(paste0('chr', 1:22), "chrX", "chrY")
human_reference_coordinates <- read_tsv('../human/reference_coordinates/t2t.tsv', 
      show_col_types = F) %>% 
    select(`Chromosome name`, `Seq length`) %>% 
    mutate(chromosome = factor(
      sprintf('chr%s', `Chromosome name`), 
      levels = chromosome_levels)
      ) %>% 
    rename(chromosome_length = `Seq length`) %>% 
    dplyr::select(-`Chromosome name`)

# Chimp
chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
chimp_reference_coordinates <- read.table('../chimp/reference_coordinates/mPanTro3.pri.cur.20231122.fasta.fai') %>%
      rowwise() %>% 
      mutate(temp_chromosome = sprintf('chr%s', toupper(strsplit(V1, 'hsa')[[1]][2])),
         chromosome = factor(temp_chromosome, 
                                   levels = chromosome_levels)
         ) %>%
  select(chromosome, V2) %>% 
  rename(chromosome_length = V2)

# Gorilla
chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
gorilla_reference_coordinates <- read.table('../gorilla/reference_coordinates/mGorGor1.pri.cur.fasta.fai') %>%
      rowwise() %>% 
      mutate(temp_chromosome = sprintf('chr%s', toupper(strsplit(V1, 'hsa')[[1]][2])),
         chromosome = factor(temp_chromosome, 
                                   levels = chromosome_levels)
         ) %>%
  select(chromosome, V2) %>% 
  rename(chromosome_length = V2) 

gorilla_reference_coordinates$chromosome[4] = 'chr5'
gorilla_reference_coordinates$chromosome[19] = 'chr17'

```


# CO
```{r, message=FALSE, warning=FALSE}
for(individual in names(sample_dict)){
  individual_crossing_overs <- read.table(sprintf("../%s/%s/output_files/co/%s_crossing_over_germline.txt", 
                                                  sample_dict[[individual]], 
                                                  individual, 
                                                  individual), 
                                          header = T) %>% 
  rename(temp_chromosome = chromosome)

    
  
  individual_with_flanking <- read.table(sprintf('../%s/%s/output_files/all_calls/%s_all_calls_germline.tsv', 
                                                 sample_dict[[individual]], 
                                                 individual, 
                                                 individual), 
                                         header =  T)
  
  before <- ref_pos_co_events(individual_with_flanking, 2)[[1]]
  after <- ref_pos_co_events(individual_with_flanking, 2)[[2]]
  
  individual_with_flanking <- individual_with_flanking %>% 
    mutate(left_jump_snp_ref = right_jump_snp_ref - (jump_snp - previous_snp),
           right_flank_ref = after + right_jump_snp_ref,
           left_flank_ref = right_jump_snp_ref - before
           )
  
  if(sample_dict[[individual]] == 'human'){
    chromosome_levels <- c(paste0('chr', 1:22), "chrX", "chrY")
    individual_crossing_overs <- individual_crossing_overs %>% 
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)
             ) %>% 
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_co <- individual_crossing_overs %>% 
      filter(Approved == 'y')
    individual_final_co <- left_join(individual_final_co, 
                                     human_reference_coordinates, 
                                     by = 'chromosome') 
  }
  
  if(sample_dict[[individual]] == 'chimp'){
    chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
    individual_crossing_overs <- individual_crossing_overs %>% 
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)
             ) %>%
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_co <- individual_crossing_overs %>% 
      filter(Approved == 'y')
    individual_final_co <- left_join(individual_final_co, 
                                     chimp_reference_coordinates, 
                                     by = 'chromosome') 

  }
  
  if(sample_dict[[individual]] == 'gorilla'){
    chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
    individual_crossing_overs <- individual_crossing_overs %>%
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)
             ) %>% 
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_co <- individual_crossing_overs %>% 
      filter(Approved == 'y')
    individual_final_co <- left_join(individual_final_co, 
                                     gorilla_reference_coordinates, 
                                     by = 'chromosome') %>% 
      convert(chr(refCpGOvl_perc)
              )
  }

  individual_ref_flanking_bed <- left_join(individual_final_co, individual_with_flanking %>% 
                                              select(read_name, left_flank_ref, right_flank_ref),
                                           by = 'read_name') %>% 
    arrange(chromosome, left_flank_ref) %>% 
    select(chromosome, left_flank_ref, right_flank_ref)
  
  individual_ref_jump_snp_bed <- left_join(individual_final_co, individual_with_flanking %>% 
                                              select(read_name, left_jump_snp_ref),
                                           by = c('read_name')) %>% 
    arrange(chromosome, left_jump_snp_ref) %>% 
    select(chromosome, left_jump_snp_ref, right_jump_snp_ref)
  
  individual_final_co_with_flanks <- inner_join(individual_final_co, 
                                                individual_with_flanking) %>% 
    arrange(chromosome, left_flank_ref)
  
   if(individual!= 'hs25' | individual!= 'hs35' | individual!= 'hs50'){
  dir.create(sprintf('../classified_reads/gcv/%s',
                     individual)
             )
   }
  
   
if(individual== 'hs25' | individual== 'hs35' | individual== 'hs50'){
  dir.create(sprintf('../sperm_reads/co/%s',
                     individual)
             )
    write.table(individual_final_co_with_flanks, 
              file = sprintf('../sperm_reads/co/%s/%s_co.tsv', 
                             individual, 
                             individual), 
              sep = '\t', 
              col.names = TRUE, 
              row.names = FALSE, 
              quote = FALSE) 
  
  write.table(individual_ref_flanking_bed, 
              file = sprintf('../sperm_reads/co/%s/%s_co_flanking_snps.bed', 
                             individual, 
                             individual), 
              sep = '\t', 
              col.names = FALSE, 
              row.names = FALSE, 
              quote = FALSE) 
  
  write.table(individual_ref_jump_snp_bed, 
              file = sprintf('../sperm_reads/co/%s/%s_co_jump_snps.bed', 
                             individual, 
                             individual), 
              sep = '\t', 
              col.names = FALSE, 
              row.names = FALSE, 
              quote = FALSE) 
  next
}
    
  write.table(individual_final_co_with_flanks, 
              file = sprintf('../classified_reads/co/%s/%s_co_germline.tsv', 
                             individual, 
                             individual), 
              sep = '\t', 
              col.names = TRUE, 
              row.names = FALSE, 
              quote = FALSE) 
  
  write.table(individual_ref_flanking_bed, 
              file = sprintf('../classified_reads/co/%s/%s_co_germline_flanking_snps.bed', 
                             individual, 
                             individual), 
              sep = '\t', 
              col.names = FALSE, 
              row.names = FALSE, 
              quote = FALSE) 
  
  write.table(individual_ref_jump_snp_bed, 
              file = sprintf('../classified_reads/co/%s/%s_co_germline_jump_snps.bed', 
                             individual, 
                             individual), 
              sep = '\t', 
              col.names = FALSE, 
              row.names = FALSE, 
              quote = FALSE) 
} 
```

# GCV
```{r, message=FALSE, warning=FALSE}
for(individual in names(sample_dict)){
  
  individual_gene_conversions <- read.table(
    sprintf("../%s/%s/output_files/gcv/%s_gene_conversion_germline.txt", 
            sample_dict[[individual]], 
            individual, 
            individual),
    header = T) %>% 
  rename(temp_chromosome = chromosome) 
  
  individual_gene_conversions$right_jump_snp_ref <- individual_gene_conversions$right_jump_snp_ref + 
    (individual_gene_conversions$next_snp - 
       individual_gene_conversions$jump_snp)  

  
  individual_with_flanking <- read.table(
    sprintf('../%s/%s/output_files/all_calls/%s_all_calls_germline.tsv', 
            sample_dict[[individual]], 
            individual, 
            individual), 
    header =  T) %>% 
    mutate(left_jump_snp_ref = right_jump_snp_ref - (jump_snp - previous_snp)
           )
  
  individual_with_flanking$right_jump_snp_ref <- individual_with_flanking$right_jump_snp_ref + 
    (individual_with_flanking$next_snp - individual_with_flanking$jump_snp)  
  
  if(sample_dict[[individual]] == 'human'){
    chromosome_levels <- c(paste0('chr', 1:22), "chrX", "chrY")
    individual_gene_conversions <- individual_gene_conversions %>% 
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)
             ) %>% 
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
   
    individual_final_gc <- individual_gene_conversions %>% 
      filter(Approved == 'y')
    individual_final_gc <- left_join(individual_final_gc, 
                                     human_reference_coordinates, 
                                     by = 'chromosome') 
  }
  
  if(sample_dict[[individual]] == 'chimp'){
    chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
    individual_gene_conversions <- individual_gene_conversions %>% 
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)
             ) %>% 
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
   
    individual_final_gc <- individual_gene_conversions %>% 
      filter(Approved == 'y')
    individual_final_gc <- left_join(individual_final_gc, 
                                     chimp_reference_coordinates, 
                                     by = 'chromosome') 
  }
  
  if(sample_dict[[individual]] == 'gorilla'){
    chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
    individual_gene_conversions <- individual_gene_conversions %>% 
      mutate(chromosome = factor(temp_chromosome, 
        levels = chromosome_levels)
        ) %>% 
      select(-temp_chromosome)
    
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_gc <- individual_gene_conversions %>% 
      filter(Approved == 'y')
    individual_final_gc <- left_join(individual_final_gc, 
                                     gorilla_reference_coordinates, 
                                     by = 'chromosome') 
  }
  
  individual_ref_jump_snp_bed <- inner_join(individual_final_gc, 
                                            individual_with_flanking) %>% 
    arrange(chromosome, left_jump_snp_ref) %>% 
    select(chromosome, left_jump_snp_ref, right_jump_snp_ref)
    
  individual_final_gc_with_flanks <- inner_join(individual_final_gc, 
                                                individual_with_flanking) %>% 
    arrange(chromosome, left_jump_snp_ref)
  
   if(individual!= 'hs25' | individual!= 'hs35' | individual!= 'hs50'){
  dir.create(sprintf('../classified_reads/gcv/%s',
                     individual)
             )
   }
  if(individual== 'hs25' | individual== 'hs35' | individual== 'hs50'){
    dir.create(sprintf('../sperm_reads/gcv/%s',
                     individual)
    )
    write.table(individual_final_gc_with_flanks, 
                file = sprintf('../sperm_reads/gcv/%s/%s_gcv.tsv', 
                               individual, 
                               individual), 
                sep = '\t', 
                col.names = TRUE, 
                row.names = FALSE, 
                quote = FALSE )
    
    write.table(individual_ref_jump_snp_bed, 
                file = sprintf('../sperm_reads/gcv/%s/%s_gcv_jump_snps.bed', 
                               individual, 
                               individual), 
                sep = '\t', 
                col.names = FALSE, 
                row.names = FALSE, 
                quote = FALSE)
    next
    
  }
   write.table(individual_final_gc_with_flanks, 
              file = sprintf('../classified_reads/gcv/%s/%s_gcv_germline.tsv', 
                             individual, 
                             individual), 
              sep = '\t', 
              col.names = TRUE, 
              row.names = FALSE, 
              quote = FALSE )
  
  write.table(individual_ref_jump_snp_bed, 
              file = sprintf('../classified_reads/gcv/%s/%s_gcv_germline_jump_snps.bed', 
                             individual, 
                             individual), 
              sep = '\t', 
              col.names = FALSE, 
              row.names = FALSE, 
              quote = FALSE) 
} 
```




# Boundary
```{r, message=FALSE, warning=FALSE}
for(individual in names(sample_dict)){
  individual_boundaries <- read.table(sprintf("../%s/%s/output_files/boundary/%s_boundary_germline.txt", 
                                              sample_dict[[individual]],
                                              individual, 
                                              individual), 
                                      header = T) %>% 
  rename(temp_chromosome = chromosome ) 
  
  individual_with_flanking <- read.table(
    sprintf('../%s/%s/output_files/all_calls/%s_all_calls_germline.tsv', 
            sample_dict[[individual]], 
            individual, 
            individual),
    header =  T) %>% 
    mutate(left_jump_snp_ref = right_jump_snp_ref - (jump_snp - previous_snp),
           right_flank_ref = right_jump_snp_ref + 1500 ,
           left_flank_ref = right_jump_snp_ref - 1500
           )

  if(sample_dict[[individual]] == 'human'){
    chromosome_levels <- c(paste0('chr', 1:22), "chrX", "chrY")
    individual_boundaries <- individual_boundaries %>%
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)) %>% 
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_boundary <- individual_boundaries %>% 
      filter(Approved == 'y')
    individual_final_boundary <- left_join(individual_final_boundary, 
                                           human_reference_coordinates, 
                                           by = 'chromosome') 
  }
  
  if(sample_dict[[individual]] == 'chimp'){
    chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
    individual_boundaries <- individual_boundaries %>% 
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)) %>%
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_boundary <- individual_boundaries %>% 
      filter(Approved == 'y')
    individual_final_boundary <- left_join(individual_final_boundary, 
                                           chimp_reference_coordinates, 
                                           by = 'chromosome') 

  }
  
  if(sample_dict[[individual]] == 'gorilla'){
    chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
    individual_boundaries <- individual_boundaries %>% 
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)
             ) %>% 
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_boundary <- individual_boundaries %>% 
      filter(Approved == 'y')
    individual_final_boundary <- left_join(individual_final_boundary, 
                                           gorilla_reference_coordinates, 
                                           by = 'chromosome') 
  
  }
  
individual_ref_1500bp_interval_bed <- inner_join(individual_final_boundary, 
                                                 individual_with_flanking) %>% 
  arrange(chromosome, left_flank_ref) %>% 
  select(chromosome, left_flank_ref, right_flank_ref)

individual_final_boundary_with_flanks <- inner_join(individual_final_boundary, 
                                                    individual_with_flanking) %>%
  arrange(chromosome, left_jump_snp_ref)
  
  if(individual!= 'hs25' | individual!= 'hs35' | individual!= 'hs50'){
  dir.create(sprintf('../classified_reads/boundary/%s',
                     individual)
             )
  }
  
  if(individual== 'hs25' | individual== 'hs35' | individual== 'hs50'){
    dir.create(sprintf('../sperm_reads/boundary/%s',
                     individual)
             )
     write.table(individual_final_boundary_with_flanks, 
              file = sprintf('../sperm_reads/boundary/%s/%s_boundary.tsv',
                             individual,
                             individual), 
              sep = '\t', 
              col.names = TRUE, 
              row.names = FALSE, 
              quote = FALSE ) 
  
    write.table(individual_ref_1500bp_interval_bed, 
              file = sprintf('../sperm_reads/boundary/%s/%s_ref_1500bp_interval_boundary.bed',
                             individual,
                             individual), 
              sep = '\t',
              col.names = FALSE, 
              row.names = FALSE, 
              quote = FALSE )
    next
  }
  write.table(individual_final_boundary_with_flanks, 
              file = sprintf('../classified_reads/boundary/%s/%s_boundary_germline.tsv',
                             individual,
                             individual), 
              sep = '\t', 
              col.names = TRUE, 
              row.names = FALSE, 
              quote = FALSE ) 
  
  write.table(individual_ref_1500bp_interval_bed, 
              file = sprintf('../classified_reads/boundary/%s/%s_ref_1500bp_interval_boundary_germline.bed',
                             individual,
                             individual), 
              sep = '\t',
              col.names = FALSE, 
              row.names = FALSE, 
              quote = FALSE ) 
} 
```


# Complex 
```{r, message=FALSE, warning=FALSE}
for(individual in names(sample_dict)){
  individual_complex <- read.table(
    sprintf("../%s/%s/output_files/complex/%s_complex_germline.txt", 
            sample_dict[[individual]], 
            individual, 
            individual),
    header = T) %>% 
  rename(temp_chromosome = chromosome ) 
  
  individual_with_flanking <- read.table(
    sprintf('../%s/%s/output_files/all_calls/%s_all_calls_germline.tsv',
            sample_dict[[individual]],
            individual, 
            individual), 
    header =  T) 
  
  dist_to_first_snp <- first_last_snps(individual_with_flanking)[[1]]
  dist_to_last_snp <- first_last_snps(individual_with_flanking)[[2]]
  individual_with_flanking <- individual_with_flanking %>% 
    mutate(first_snp_ref = right_jump_snp_ref - dist_to_first_snp,
           last_snp_ref = right_jump_snp_ref + dist_to_last_snp)
  
  if(sample_dict[[individual]] == 'human'){
    chromosome_levels <- c(paste0('chr', 1:22), "chrX", "chrY")
    individual_complex <- individual_complex %>% 
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)
             ) %>% 
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_complex <- individual_complex %>% 
      filter(Approved == 'y')
    individual_final_complex <- left_join(individual_final_complex, 
                                          human_reference_coordinates, 
                                          by = 'chromosome') 
  }
  
  if(sample_dict[[individual]] == 'chimp'){
    chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
    individual_complex <- individual_complex %>% 
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)
             ) %>% 
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_complex <- individual_complex %>% 
      filter(Approved == 'y')
    individual_final_complex <- left_join(individual_final_complex, 
                                          chimp_reference_coordinates, 
                                          by = 'chromosome') 
  }
  
  if(sample_dict[[individual]] == 'gorilla'){
    chromosome_levels <- c("chr1", 'chr2A', 'chr2B', paste0('chr', 3:22), "chrX", "chrY")
    individual_complex <- individual_complex %>%
      mutate(chromosome = factor(temp_chromosome, 
                                 levels = chromosome_levels)) %>% 
      select(-temp_chromosome)
    individual_with_flanking$chromosome  <- factor(individual_with_flanking$chromosome, 
                                                   levels = chromosome_levels) 
    
    individual_final_complex <- individual_complex %>% 
      filter(Approved == 'y')
    individual_final_complex <- left_join(individual_final_complex, 
                                          gorilla_reference_coordinates, 
                                          by = 'chromosome') %>% 
      convert(chr(refCpGOvl_perc)
            )
  }
  
  
  individual_final_complex_first_last_snp <- inner_join(individual_final_complex, 
                                                        individual_with_flanking) %>%
    arrange(chromosome, first_snp_ref)
  individual_final_complex_first_last_snp_bed <- inner_join(individual_final_complex, 
                                                            individual_with_flanking) %>% 
  arrange(chromosome, first_snp_ref) %>% 
  select(chromosome, first_snp_ref, last_snp_ref)
  
  
  if(individual!= 'hs25' | individual!= 'hs35' | individual!= 'hs50'){
  dir.create(sprintf('../classified_reads/complex/%s',
                     individual)
             )
  }
  
  if(individual== 'hs25' | individual== 'hs35' | individual== 'hs50'){
     dir.create(sprintf('../sperm_reads/complex/%s',
                     individual)
             )
     write.table(individual_final_complex_first_last_snp, 
              file = sprintf('../sperm_reads/complex/%s/%s_complex.tsv', 
                                                                      individual, 
                                                                      individual), 
              sep = '\t', 
              col.names = TRUE, 
              row.names = FALSE, 
              quote = FALSE) 
  write.table(individual_final_complex_first_last_snp_bed, 
              file = sprintf('../sperm_reads/complex/%s/%s_jump_snps_complex.bed', 
                             individual, 
                             individual), 
            sep = '\t', 
            col.names = FALSE, 
            row.names = FALSE, 
            quote = FALSE) 
  next
  }
  
  write.table(individual_final_complex_first_last_snp, 
              file = sprintf('../classified_reads/complex/%s/%s_complex_germline.tsv', 
                                                                      individual, 
                                                                      individual), 
              sep = '\t', 
              col.names = TRUE, 
              row.names = FALSE, 
              quote = FALSE) 
  write.table(individual_final_complex_first_last_snp_bed, 
              file = sprintf('../classified_reads/complex/%s/%s_jump_snps_complex_germline.bed', 
                             individual, 
                             individual), 
            sep = '\t', 
            col.names = FALSE, 
            row.names = FALSE, 
            quote = FALSE) 
} 
```
  



